<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( [
    'key' => 'group_draad_az_area',
    'title' => __( 'Buurtcode invoervelden', 'draad' ),
    'fields' => [
        [
            'key' => 'field_draad_az_general_tab_area',
            'label' => __( 'Algemeen', 'draad' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'top',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_neighbourhood_code_area',
            'label' => __( 'Buurtcode', 'draad-az' ),
            'name' => 'neigbourhood_code',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '50',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_draad_az_text_number_area',
            'label' => __( 'Tekstnummer', 'draad-az' ),
            'name' => 'text_number',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '50',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_draad_az_version_1_tab_area',
            'label' => __( 'Versie 1', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'top',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_heat_solution_area',
            'label' => __( 'Warmteoplossing', 'draad-az' ),
            'name' => 'heat_solution',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_draad_az_version_3_tab_area',
            'label' => __( 'Versie 3', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'top',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_text_number_v3_area',
            'label' => __( 'Tekstnummer voor de 3e versie van de adreszoeker', 'draad-az' ),
            'name' => 'text_number_v3',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '50',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_draad_az_heat_solution_dropdown_area',
            'label' => __( 'Warmte oplossing - dropdown ( Let op dit is alleen voor de 3e versie van de adreszoeker )', 'draad-az' ),
            'name' => 'heat_solution_dropdown',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '50',
                'class' => '',
                'id' => '',
            ],
            'choices' => [
                'bestaand-warmtenet' => __( 'Bestaand warmtenet', 'draad-az' ),
                'elektrische-warmtepomp' => __( 'Elektrische warmtepomp', 'draad-az' ),
                'mix-van-warmtenetten-en-warmtepompen' => __( 'Mix van warmtenetten en warmtepompen', 'draad-az' ),
                'warmtenet-na-2030' => __( 'Warmtenet na 2030', 'draad-az' ),
                'warmtenet' => __( 'Warmtenet', 'draad-az' ),
                'hybride-warmtepomp' => __( 'Hybride warmtepomp', 'draad-az' ),
            ],
            'default_value' => false,
            'return_format' => 'array',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'draad_az_area',
            ],
        ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
] );