<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( [
    'key' => 'group_draad_az_area',
    'title' => __( 'Buurtcode invoervelden', 'draad-adreszoeker' ),
    'fields' => [
        [
            'key' => 'field_draad_az_neighbourhood_code_area',
            'label' => __( 'Buurtcode', 'draad-adreszoeker' ),
            'name' => 'neigbourhood_code',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '33.333',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_draad_az_text_number_area',
            'label' => __( 'Tekstnummer', 'draad-adreszoeker' ),
            'name' => 'text_number',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '33.333',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_draad_az_heat_solution_dropdown_area',
            'label' => __( 'Warmte oplossing - dropdown', 'draad-adreszoeker' ),
            'name' => 'heat_solution_dropdown',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '33.333',
                'class' => '',
                'id' => '',
            ],
            'choices' => draad_az_return_heat_solutions_acf(),
            'default_value' => false,
            'return_format' => 'array',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ],
        [
            'key' => 'field_draad_az_heat_solution_tiles',
            'label' => 'Tegels',
            'name' => 'tiles',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => 'In het resultaat van de adreszoeker worden maximaal 2 tegels getoond.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 2,
            'collapsed' => '',
            'button_label' => 'Tegel toevoegen',
            'rows_per_page' => 20,
            'sub_fields' => [
                [
                    'key' => 'field_draad_az_heat_solution_tiles_post',
                    'label' => 'Post',
                    'name' => 'post',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => 'Waar moet deze tegel naartoe linken.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'post_type' => get_post_types( [ 'public' => true ], 'names' ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => [],
                    'parent_repeater' => 'field_draad_az_heat_solution_tiles',
                ],
                [
                    'key' => 'field_draad_az_heat_solution_tiles_label',
                    'label' => 'Label',
                    'name' => 'label',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'Label boven de titel van de tegel.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_draad_az_heat_solution_tiles',
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'draad_az_area',
            ],
        ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
] );