<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Prevent direct access
}

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( [
    'key' => 'group_draad_az_text_1',
    'title' => __( 'Adreszoeker - instellingen', 'draad-az' ),
    'fields' => [
        [
            'key' => 'field_draad_az_general_text_tab_text_1',
            'label' => __( 'Algemene - tekst', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'left',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_address_title_text_1',
            'label' => __( 'Adreszoeker standaard titel', 'draad-az' ),
            'name' => 'address_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 'Aan de slag!',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_draad_az_isolation_tab_text_1',
            'label' => __( 'Isolatie tab', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'left',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_isolation_text_1',
            'label' => __( 'Isolatie', 'draad-az' ),
            'name' => 'isolatie',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'row',
            'sub_fields' => [
                [
                    'key' => 'field_draad_az_icon_isolation_text_1',
                    'label' => __( 'icoon', 'draad-az' ),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'icon_sets' => [
                        0 => 'fas',
                        1 => 'far',
                        2 => 'fal',
                    ],
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 1,
                    'show_preview' => 1,
                    'enqueue_fa' => 1,
                    'fa_live_preview' => '',
                    'choices' => [
                    ],
                ],
                [
                    'key' => 'field_draad_az_repeater_isolation_text_1',
                    'label' => __( 'Teksten per bouwperiode en warmteoplossing', 'draad-az' ),
                    'name' => 'repeater',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'subfield_draad_az_heat_solution_dropdown_isolation_text_1',
                    'button_label' => __( 'Nieuwe regel', 'draad-az' ),
                    'rows_per_page' => 20,
                    'sub_fields' => [
                        [
                            'key' => 'subfield_draad_az_heat_solution_dropdown_isolation_text_1',
                            'label' => __( 'Warmteoplossing', 'draad-az' ),
                            'name' => 'heat_solution_dropdown',
                            'aria-label' => '',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'choices' => [
                                'bestaand-warmtenet' => __( 'Bestaand warmtenet', 'draad-az' ),
                                'elektrische-warmtepomp' =>  __( 'Elektrische warmtepomp', 'draad-az' ),
                                'mix-van-warmtenetten-en-warmtepompen' => __( 'Mix van warmtenetten en warmtepompen', 'draad-az' ),
                                'warmtenet-na-2030' => __( 'Warmtenet na 2030', 'draad-az' ),
                                'warmtenet' => __( 'Warmtenet', 'draad-az' ),
                                'hybride-warmtepomp' => __( 'Hybride warmtepomp', 'draad-az' ),
                            ],
                            'default_value' => [
                            ],
                            'return_format' => 'value',
                            'allow_custom' => 0,
                            'layout' => 'horizontal',
                            'toggle' => 0,
                            'save_custom' => 0,
                            'custom_choice_button_text' => __( 'Nieuwe keuze toevoegen', 'draad-az' ),
                            'parent_repeater' => 'field_draad_az_repeater_isolation_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_content_isolation_text_1',
                            'label' => __( 'Content', 'draad-az' ),
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '65',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                            'parent_repeater' => 'field_draad_az_repeater_isolation_text_1',
                        ],
                        [
                            'key' => 'field_draad_az_period_isolation_text_1',
                            'label' => __( 'Bouwperiode', 'draad-az' ),
                            'name' => 'period',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '35',
                                'class' => '',
                                'id' => '',
                            ],
                            'taxonomy' => 'draad_az_build_period',
                            'add_term' => 0,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'checkbox',
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional_target' => [
                            ],
                            'parent_repeater' => 'field_draad_az_repeater_isolation_text_1',
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'field_draad_az_ventilation_tab_text_1',
            'label' => __( 'Ventilatie tab', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'left',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_ventilation_text_1',
            'label' => __( 'Ventilatie', 'draad-az' ),
            'name' => 'ventilatie',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'row',
            'sub_fields' => [
                [
                    'key' => 'field_draad_az_icon_ventilation_text_1',
                    'label' => __( 'icoon', 'draad-az' ),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'icon_sets' => [
                        0 => 'fas',
                        1 => 'far',
                        2 => 'fal',
                    ],
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 1,
                    'show_preview' => 1,
                    'enqueue_fa' => 1,
                    'fa_live_preview' => '',
                    'choices' => [
                    ],
                ],
                [
                    'key' => 'field_draad_az_repeater_ventilation_text_1',
                    'label' => __( 'Teksten per bouwperiode en warmteoplossing', 'draad-az' ),
                    'name' => 'repeater',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'subfield_draad_az_heat_solution_dropdown_ventilation_text_1',
                    'button_label' => 'Nieuwe regel',
                    'rows_per_page' => 20,
                    'sub_fields' => [
                        [
                            'key' => 'subfield_draad_az_heat_solution_dropdown_ventilation_text_1',
                            'label' => __( 'Warmteoplossing', 'draad-az' ),
                            'name' => 'heat_solution_dropdown',
                            'aria-label' => '',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'choices' => [
                                'bestaand-warmtenet' => __( 'Bestaand warmtenet', 'draad-az' ),
                                'elektrische-warmtepomp' =>  __( 'Elektrische warmtepomp', 'draad-az' ),
                                'mix-van-warmtenetten-en-warmtepompen' => __( 'Mix van warmtenetten en warmtepompen', 'draad-az' ),
                                'warmtenet-na-2030' => __( 'Warmtenet na 2030', 'draad-az' ),
                                'warmtenet' => __( 'Warmtenet', 'draad-az' ),
                                'hybride-warmtepomp' => __( 'Hybride warmtepomp', 'draad-az' ),
                            ],
                            'default_value' => [
                            ],
                            'return_format' => 'value',
                            'allow_custom' => 0,
                            'layout' => 'horizontal',
                            'toggle' => 0,
                            'save_custom' => 0,
                            'custom_choice_button_text' => __( 'Nieuwe keuze toevoegen', 'draad-az' ),
                            'parent_repeater' => 'field_draad_az_repeater_ventilation_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_content_ventilation_text_1',
                            'label' => __( 'Content', 'draad-az' ),
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '65',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                            'parent_repeater' => 'field_draad_az_repeater_ventilation_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_period_ventilation_text_1',
                            'label' => __( 'Bouwperiode', 'draad-az' ),
                            'name' => 'period',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '35',
                                'class' => '',
                                'id' => '',
                            ],
                            'taxonomy' => 'draad_az_build_period',
                            'add_term' => 0,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'checkbox',
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional_target' => [
                            ],
                            'parent_repeater' => 'field_draad_az_repeater_ventilation_text_1',
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'field_draad_az_raise_tab_text_1',
            'label' => __( 'Opwekken tab', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'left',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_raise_text_1',
            'label' => __( 'Opwekken', 'draad-az' ),
            'name' => 'opwekken',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'row',
            'sub_fields' => [
                [
                    'key' => 'field_draad_az_icon_raise_text_1',
                    'label' => __( 'icoon', 'draad-az' ),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'icon_sets' => [
                        0 => 'fas',
                        1 => 'far',
                        2 => 'fal',
                    ],
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 1,
                    'show_preview' => 1,
                    'enqueue_fa' => 1,
                    'fa_live_preview' => '',
                    'choices' => [
                    ],
                ],
                [
                    'key' => 'field_draad_az_repeater_raise_text_1',
                    'label' => __( 'Teksten per bouwperiode en warmteoplossing', 'draad-az' ),
                    'name' => 'repeater',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'subfield_draad_az_heat_solution_dropdown_raise_text_1',
                    'button_label' => __( 'Nieuwe regel', 'draad-az' ),
                    'rows_per_page' => 20,
                    'sub_fields' => [
                        [
                            'key' => 'subfield_draad_az_heat_solution_dropdown_raise_text_1',
                            'label' => __( 'Warmteoplossing', 'draad-az' ),
                            'name' => 'heat_solution_dropdown',
                            'aria-label' => '',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'choices' => [
                                'bestaand-warmtenet' => __( 'Bestaand warmtenet', 'draad-az' ),
                                'elektrische-warmtepomp' =>  __( 'Elektrische warmtepomp', 'draad-az' ),
                                'mix-van-warmtenetten-en-warmtepompen' => __( 'Mix van warmtenetten en warmtepompen', 'draad-az' ),
                                'warmtenet-na-2030' => __( 'Warmtenet na 2030', 'draad-az' ),
                                'warmtenet' => __( 'Warmtenet', 'draad-az' ),
                                'hybride-warmtepomp' => __( 'Hybride warmtepomp', 'draad-az' ),
                            ],
                            'default_value' => [
                            ],
                            'return_format' => 'value',
                            'allow_custom' => 0,
                            'layout' => 'horizontal',
                            'toggle' => 0,
                            'save_custom' => 0,
                            'custom_choice_button_text' => __( 'Nieuwe keuze toevoegen', 'draad-az' ),
                            'parent_repeater' => 'field_draad_az_repeater_raise_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_content_raise_text_1',
                            'label' => __( 'Content', 'draad-az' ),
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '65',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                            'parent_repeater' => 'field_draad_az_repeater_raise_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_period_raise_text_1',
                            'label' => __( 'Bouwperiode', 'draad-az' ),
                            'name' => 'period',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '35',
                                'class' => '',
                                'id' => '',
                            ],
                            'taxonomy' => 'draad_az_build_period',
                            'add_term' => 0,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'checkbox',
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional_target' => [
                            ],
                            'parent_repeater' => 'field_draad_az_repeater_raise_text_1',
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'field_draad_az_heat_tab_text_1',
            'label' => __( 'Verwarmen tab', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'left',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_heat_text_1',
            'label' => __( 'Verwarmen', 'draad-az' ),
            'name' => 'verwarmen',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'row',
            'sub_fields' => [
                [
                    'key' => 'field_draad_az_icon_heat_text_1',
                    'label' => __( 'icoon', 'draad-az' ),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'icon_sets' => [
                        0 => 'fas',
                        1 => 'far',
                        2 => 'fal',
                    ],
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 1,
                    'show_preview' => 1,
                    'enqueue_fa' => 1,
                    'fa_live_preview' => '',
                    'choices' => [
                    ],
                ],
                [
                    'key' => 'field_draad_az_repeater_heat_text_1',
                    'label' => __( 'Teksten per bouwperiode en warmteoplossing', 'draad-az' ),
                    'name' => 'repeater',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'sub_field_draad_az_heat_solution_dropdown_heat_text_1',
                    'button_label' => __( 'Nieuwe regel', 'draad-az' ),
                    'rows_per_page' => 20,
                    'sub_fields' => [
                        [
                            'key' => 'sub_field_draad_az_heat_solution_dropdown_heat_text_1',
                            'label' => __( 'Warmteoplossing', 'draad-az' ),
                            'name' => 'heat_solution_dropdown',
                            'aria-label' => '',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'choices' => [
                                'bestaand-warmtenet' => __( 'Bestaand warmtenet', 'draad-az' ),
                                'elektrische-warmtepomp' =>  __( 'Elektrische warmtepomp', 'draad-az' ),
                                'mix-van-warmtenetten-en-warmtepompen' => __( 'Mix van warmtenetten en warmtepompen', 'draad-az' ),
                                'warmtenet-na-2030' => __( 'Warmtenet na 2030', 'draad-az' ),
                                'warmtenet' => __( 'Warmtenet', 'draad-az' ),
                                'hybride-warmtepomp' => __( 'Hybride warmtepomp', 'draad-az' ),
                            ],
                            'default_value' => [
                            ],
                            'return_format' => 'value',
                            'allow_custom' => 0,
                            'layout' => 'horizontal',
                            'toggle' => 0,
                            'save_custom' => 0,
                            'custom_choice_button_text' => __( 'Nieuwe keuze toevoegen', 'draad-az' ),
                            'parent_repeater' => 'field_draad_az_repeater_heat_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_content_heat_text_1',
                            'label' => __( 'Content', 'draad-az' ),
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '65',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                            'parent_repeater' => 'field_draad_az_repeater_heat_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_period_heat_text_1',
                            'label' => __( 'Bouwperiode', 'draad-az' ),
                            'name' => 'period',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '35',
                                'class' => '',
                                'id' => '',
                            ],
                            'taxonomy' => 'draad_az_build_period',
                            'add_term' => 0,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'checkbox',
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional_target' => [
                            ],
                            'parent_repeater' => 'field_draad_az_repeater_heat_text_1',
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'field_draad_az_cook_tab_text_1',
            'label' => __( 'Koken tab', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'left',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_cook_text_1',
            'label' => __( 'Koken', 'draad-az' ),
            'name' => 'koken',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'row',
            'sub_fields' => [
                [
                    'key' => 'field_draad_az_icon_cook_text_1',
                    'label' => __( 'icoon', 'draad-az' ),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'icon_sets' => [
                        0 => 'fas',
                        1 => 'far',
                        2 => 'fal',
                    ],
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 1,
                    'show_preview' => 1,
                    'enqueue_fa' => 1,
                    'fa_live_preview' => '',
                    'choices' => [
                    ],
                ],
                [
                    'key' => 'field_draad_az_repeater_cook_text_1',
                    'label' => __( 'Teksten per bouwperiode en warmteoplossing', 'draad-az' ),
                    'name' => 'repeater',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'sub_field_draad_az_heat_solution_dropdown_cook_text_1',
                    'button_label' => __( 'Nieuwe regel', 'draad-az' ),
                    'rows_per_page' => 20,
                    'sub_fields' => [
                        [
                            'key' => 'sub_field_draad_az_heat_solution_dropdown_cook_text_1',
                            'label' => __( 'Warmteoplossing', 'draad-az' ),
                            'name' => 'heat_solution_dropdown',
                            'aria-label' => '',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'choices' => [
                                'bestaand-warmtenet' => __( 'Bestaand warmtenet', 'draad-az' ),
                                'elektrische-warmtepomp' =>  __( 'Elektrische warmtepomp', 'draad-az' ),
                                'mix-van-warmtenetten-en-warmtepompen' => __( 'Mix van warmtenetten en warmtepompen', 'draad-az' ),
                                'warmtenet-na-2030' => __( 'Warmtenet na 2030', 'draad-az' ),
                                'warmtenet' => __( 'Warmtenet', 'draad-az' ),
                                'hybride-warmtepomp' => __( 'Hybride warmtepomp', 'draad-az' ),
                            ],
                            'default_value' => [
                            ],
                            'return_format' => 'value',
                            'allow_custom' => 0,
                            'layout' => 'horizontal',
                            'toggle' => 0,
                            'save_custom' => 0,
                            'custom_choice_button_text' => __( 'Nieuwe keuze toevoegen', 'draad-az' ),
                            'parent_repeater' => 'field_draad_az_repeater_cook_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_content_cook_text_1',
                            'label' => __( 'Content', 'draad-az' ),
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '65',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                            'parent_repeater' => 'field_draad_az_repeater_cook_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_period_cook_text_1',
                            'label' => __( 'Bouwperiode', 'draad-az' ),
                            'name' => 'period',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '35',
                                'class' => '',
                                'id' => '',
                            ],
                            'taxonomy' => 'draad_az_build_period',
                            'add_term' => 0,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'checkbox',
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional_target' => [
                            ],
                            'parent_repeater' => 'field_draad_az_repeater_cook_text_1',
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'field_draad_az_subsidies_tab_text_1',
            'label' => __( 'Subsidies tab', 'draad-az' ),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'left',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_subsidies_text_1',
            'label' => __( 'Subsidies', 'draad-az' ),
            'name' => 'subsidies',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'row',
            'sub_fields' => [
                [
                    'key' => 'field_draad_az_icon_subsidies_text_1',
                    'label' => __( 'icoon', 'draad-az' ),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'icon_sets' => [
                        0 => 'fas',
                        1 => 'far',
                        2 => 'fal',
                    ],
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 1,
                    'show_preview' => 1,
                    'enqueue_fa' => 1,
                    'fa_live_preview' => '',
                    'choices' => [
                    ],
                ],
                [
                    'key' => 'field_draad_az_repeater_subsidies_text_1',
                    'label' => __( 'Teksten per bouwperiode en warmteoplossing', 'draad-az' ),
                    'name' => 'repeater',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'subfield_draad_az_heat_solution_dropdown_subsidies_text_1',
                    'button_label' => 'Nieuwe regel',
                    'rows_per_page' => 20,
                    'sub_fields' => [
                        [
                            'key' => 'subfield_draad_az_heat_solution_dropdown_subsidies_text_1',
                            'label' => __( 'Warmteoplossing', 'draad-az' ),
                            'name' => 'heat_solution_dropdown',
                            'aria-label' => '',
                            'type' => 'checkbox',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'choices' => [
                                'bestaand-warmtenet' => __( 'Bestaand warmtenet', 'draad-az' ),
                                'elektrische-warmtepomp' =>  __( 'Elektrische warmtepomp', 'draad-az' ),
                                'mix-van-warmtenetten-en-warmtepompen' => __( 'Mix van warmtenetten en warmtepompen', 'draad-az' ),
                                'warmtenet-na-2030' => __( 'Warmtenet na 2030', 'draad-az' ),
                                'warmtenet' => __( 'Warmtenet', 'draad-az' ),
                                'hybride-warmtepomp' => __( 'Hybride warmtepomp', 'draad-az' ),
                            ],
                            'default_value' => [
                            ],
                            'return_format' => 'value',
                            'allow_custom' => 0,
                            'layout' => 'horizontal',
                            'toggle' => 0,
                            'save_custom' => 0,
                            'custom_choice_button_text' => __( 'Nieuwe keuze toevoegen', 'draad-az' ),
                            'parent_repeater' => 'field_draad_az_repeater_subsidies_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_content_subsidies_text_1',
                            'label' => 'Content',
                            'name' => 'content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '65',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 0,
                            'delay' => 0,
                            'parent_repeater' => 'field_draad_az_repeater_subsidies_text_1',
                        ],
                        [
                            'key' => 'subfield_draad_az_period_subsidies_text_1',
                            'label' => __( 'Bouwperiode', 'draad-az' ),
                            'name' => 'period',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '35',
                                'class' => '',
                                'id' => '',
                            ],
                            'taxonomy' => 'draad_az_build_period',
                            'add_term' => 0,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'checkbox',
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional_target' => [
                            ],
                            'parent_repeater' => 'field_draad_az_repeater_subsidies_text_1',
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'field_draad_az_house_tab_text_1',
            'label' => 'Wat voor type huis heb jij?',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'top',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_draad_az_house_text_1',
            'label' => __( 'Type huis', 'draad-az' ),
            'name' => 'huis',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'block',
            'sub_fields' => [
                [
                    'key' => 'subfield_draad_az_content_house_text_1',
                    'label' => __( 'Tekst boven de tegel', 'draad-az' ),
                    'name' => 'content',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'delay' => 0,
                ],
            ],
        ],
        [
            'key' => 'field_draad_az_tiles_text_1',
            'label' => __( 'Tegels', 'draad-az' ),
            'name' => 'tiles',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'subfield_draad_az_title_tiles_text_1',
            'button_label' => __( 'Nieuwe regel', 'draad-az' ),
            'rows_per_page' => 20,
            'sub_fields' => [
                [
                    'key' => 'subfield_draad_az_title_tiles_text_1',
                    'label' => 'Titel',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_draad_az_tiles_text_1',
                ],
                [
                    'key' => 'subfield_draad_az_content_tiles_text_1',
                    'label' => __( 'Knop', 'draad-az' ),
                    'name' => 'button',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'array',
                    'parent_repeater' => 'field_draad_az_tiles_text_1',
                ],
                [
                    'key' => 'subfield_draad_az_image_tiles_text_1',
                    'label' => __( 'Afbeelding', 'draad-az' ),
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'parent_repeater' => 'field_draad_az_tiles_text_1',
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'draad-adreszoeker-instellingen',
            ],
        ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
] );